### ISSUE TITLE
Server Error: no parameter named 'username'

### ISSUE THREAD

**Issue by SiteDesignUSA** [jamtur01/jamtur01-httpauth#8]
Hi,

Got this when using example from github and r10k to download version

<pre>
mod 'jamtur01-httpauth', '0.0.3'
</pre>

from the puppet forge. 

`Error 500 on SERVER: Server Error: no parameter named 'username'`

Could you update the forge?

Thanks,
-TJ

**Comment by jamtur01** [comment]
Released to forge.
